#!/bin/bash

# Check for existence of needed tools, so we can give a better error
# message than the shell will.
tools="make cmake"
for tool in $tools
do
	if ! type -p $tool > /dev/null
	then
		echo "FAILED to find build tool '$tool'!"
		echo
		echo BOOTSTRAP FAILED!
		echo
		exit 1
	fi
done

# Build generated header files
(
	cd src
	./querydef.pl
	./ssqls.pl
)

# Ready to rock.  Tell user how to proceed.
cat <<MSG
Source tree set up for building.  You may now proceed to the CMake
step.  For example:

     $ mkdir build
     $ cd build
     $ cmake ..
     $ make
     
MSG