#!/bin/bash
if [ -z "$1" -o -z "$2" ]
then
	cat <<USAGE
usage: $0 infile outfile

    outfile will be a version of the infile suitable for xincluding
    into the DocBook userman during XSLT processing.  The leading block
    comment plus the blank line following it is removed, and all tabs
    are converted to four spaces.

USAGE
fi

SRCFILE=$1
TXTFILE=$2
CLINE=`grep -n '\*\*/' $SRCFILE | cut -f1 -d:`
expand -t4 $SRCFILE | tail -n +$((CLINE+2)) > $TXTFILE

